---
- name: Install dependencies
  ansible.builtin.apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - gnupg-agent
      - software-properties-common
  tags:
    - grafana
    - grafana-system

- name: DEB architecture
  ansible.builtin.shell: dpkg --print-architecture
  register: deb_architecture
  changed_when: false
  tags:
    - grafana
    - grafana-install

- name: Add Grafana archive key
  ansible.builtin.get_url:
    url: "{{ grafana_key_url }}"
    dest: "{{ grafana_key_file }}"
  tags:
    - grafana
    - grafana-install

- name: Add Grafana gpg key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  tags:
    - grafana
    - grafana-install

- name: Add MongoDB apt repo
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by={{ grafana_key_file }}] https://apt.grafana.com stable main"
    state: present
    filename: grafana
    update_cache: yes
  tags:
    - grafana
    - grafana-install

- name: Install Grafana
  ansible.builtin.apt:
    update_cache: yes
    name:
      # - grafana-enterprise
      - grafana
  tags:
    - grafana
    - grafana-install

- name: Start and enable Grafana service
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes
  tags:
    - grafana
    - grafana-service
